import { dealer, product } from "../../../../../../schema/schema";

export const getProductListsSchema = {
  id: product.id,
  running_number: product.running_number,
  factory_number: product.factory_number,
  short_name: product.short_name,
  name: product.name,
  model: product.model,
  brand: product.brand,
  cost: product.cost,
  sale_price: product.sale_price,
  technician_price: product.technician_price,
  price2: product.price2,
  special_price_one: product.special_price_one,
  special_price_two: product.special_price_two,
  authentic_code: product.authentic_code,
  category_id: product.category_id,
  secret_code: product.secret_code,
  special_search: product.special_search,
  created_by_id: product.created_by_id,
  dealer_id: product.dealer_id,
  last_price: product.last_price,
  unit_big: product.unit_big,
  unit_small: product.unit_small,
  substitute_product_name: product.substitute_product_name,
  storage_location: product.storage_location,
  created_at: product.created_at,
  updated_at: product.updated_at,
  deleted_at: product.deleted_at,
  dealer: {
    id: dealer.id,
    name: dealer.name,
    address: dealer.address,
    phone: dealer.phone,
  },
};
